- app/Http/Controllers/References/PoskoController.php
- app/Models/Category.php
- app/Models/Content.php
- app/Models/ContentGeometry.php
- app/Models/ContentGeometryCoordinate.php
- app/Models/Posko.php
- composer.json
- database/migrations/2014_10_12_000000_create_users_table.php
- database/migrations/2018_05_29_105351_add_column_name_table.php
- database/migrations/2018_05_30_001522_add_time_zone_on_content_table.php
- database/seeds/DatabaseSeeder.php
- database/seeds/Original/CategoryTableSeeder.php
- routes/web.php
- tests/TestCase.php
- tests/Unit/PoskoTest.php
#TODO
create TDD for second add posko data to update the data into database
> TDD for first add posko and coordinate

- docs/contributing.md
- readme.md
Menambahkan dokumentasi bagaimana berkontribusi.
- [Added] contributing.md :doc:
- [Modified] readme.md :doc:
> Menambahkan dokumentasi bagaimana cara berkontribusi

- docs/contributing.md
Membenahi tampilan `Contoh commit message` di file contributing.md
> [Hot-Fixed] messy preview on contributing.md :doc:

- LICENSE.md
- readme.md
Mengubah file License menjadi markdown
- [Changed] file LICENSE menjadi LICENSE.MD
- [Changed] file readme.md
> [Changed] License file

- docs/devsetuplinux.md
- readme.md
menambahkan git init pada step 6, dan menambahkan langkah installasi npm di ubuntu
[Changed] Readme.md
> [Changed] Readme.md

- public/js/app.js
- resources/views/layouts/app.blade.php
- resources/views/layouts/homescript.blade.php
- Penambahan tombol untuk menampilkan extent layer KRB, TNGM, dan
Posko pada Navbar
- Menambahkan list basemap berupa Google Tile (Streets, Satellite,
Hybrid, dan Terrain)
- Perbaikan [pr29 1] & [pr29 2]
- Perbaikan [pr30 1]
WTK: @banumelody , @lantip , @endoch
> [Fixed] Navbar extent button & Google Basemap 

- readme.md
menambah langkah jika ingin berkontribusi, dan menambah langkah jika hanya ingin menjalankan aplikasi
WTK @djenova
[Modified] readme.md
> [Modified] readme.md

- docs/devsetuplinux.md
Update devsetuplinux.md untuk Arch Linux
> Update dokumentasi Arch Linux

- public/js/app.js
- resources/views/layouts/app.blade.php
- resources/views/layouts/homescript.blade.php
mengubah metode zooming map berdasar perubahan nilai overlay control
dari yang semula zooming dipicu dari dropdown header
> map overlay change event for zooming maps

- .gitignore
- composer.lock
- readme.md
Sesuai rekomendasi di dokumentasi https://laravel.com/docs/5.5/deployment#optimization
> In addition to optimizing the autoloader, you should always be sure to include a  composer.lock file in your project's source control repository. Your project's dependencies can be installed much faster when a composer.lock file is present.
Sehingga proses command `composer install` juga jadi lebih cepat (yang lama adalah `composer update`), karena informasi packages sudah dilock di `composer.lock`. Jika terjadi konflik, tinggal `composer update` lalu push versi terbaru.
WTK: @DyanGalih @banumelody - ini bingung mensyen siapa yes 😀
> [Added] Menurut dokumentasi Laravel, composer.lock bagusnya diinclude ke Git

- .env.example
- resources/views/layouts/footer.blade.php
.env ditambahkan FACEBOOK
WTK @endoch 
WIP @Djenova
> [Added] link facebook footer

- public/css/app.css
- resources/assets/sass/_footer.scss
- resources/views/layouts/footer.blade.php
- menambah css footer (jalankan npm run dev)
> [ Added ] Telegram Icon di Footer

- app/Models/User.php
**Work In Progress**
Perlu penyesuaian untuk model `App\Models\User` karena _redundant_ dengan default bawaan laravel `App\User`. Cukup 1 saja yang dipakai.
> [WIP] Fix redundant Model App\Models\User dengan App\User

- readme.md
Readme, tambahkan keterangan minimum requirement versi untuk MySQL atau MariaDB (fix issue #59)
WTK: @banumelody @endoch @harsxv
> [Changed] Readme, tambahkan keterangan minimum requirement MariaDB

- app/Http/Controllers/HomeController.php
- resources/views/aboutus.blade.php
WTK @DyanGalih @endoch @harsxv
> [Added] layout untuk halaman about-us

- app/Http/Controllers/HomeController.php
- app/Http/Controllers/PlaceController.php
- app/Models/Place.php
- resources/views/detail.blade.php
- resources/views/errors/404.blade.php
- resources/views/posko.blade.php
- routes/web.php
- tests/Unit/Models/PlaceTest.php
- Menambahkan halaman 404
- Menambahkan unit test `getPlaceByCode` untuk Model Place
- Menambahkan `getPlaceByCode` di Model Place
- Menambahkan PlaceController
- Menampilkan list nama posko di halaman daftar posko dan detail posko
WTK: @yohang88 @DyanGalih @endoch @lantip @resxar 
Monggo direview
> [Added] Posko/PlaceController

- resources/views/layouts/app.blade.php
- resources/views/layouts/homescript.blade.php
- Memindah letak script app.js dari homescript.blade.php ke
app.blade.php
- Memperbaiki collapse navbar button yang tidak respon ketika di-klik
pada tampilan mobile di halaman selain peta/home
WTK: @endoch, @lantip, @banumelody
> [Changed] Script untuk app.js

- app/Http/Controllers/HomeController.php
- resources/views/layouts/app.blade.php
- resources/views/search.blade.php
- routes/web.php
Sebelumnya search menggunakan get, kemudian sekarang sudah  menggunakan post sehingga bisa menggunakan token csrf
[Changed] Route method from get to post web.php
[Changed] HomeController.php function search menambahkan parameter Request
[Changed] Menyesuaikan app.blade.php menggunakan metode post
> [Fixed] Search Controller, Route and View

- app/Http/Controllers/AdminController.php
- app/Providers/AppServiceProvider.php
- composer.lock
- resources/views/admin/apps/edit.blade.php
- resources/views/admin/apps/posko.blade.php
- routes/web.php
nambah dikit biar nganu
WTK @banumelody @DyanGalih @endoch @Djenova
> [Added] fitur edit&update posko

- resources/views/layouts/app.blade.php
- resources/views/layouts/homescript.blade.php
cara barbar membuat link pada popup posko ke halaman detail info posko menjadi dinamis.
sesuai dengan issue https://github.com/NgeSEC/relawan/issues/71
harap di refactor di kemudian hari
> membuat url detail info posko dari popup menjadi dinamis

- database/migrations/2019_02_16_234923_add_laravolt_foreign_to_content_geometry_coordinates.php
Berdasarkan issue 😉  : https://github.com/NgeSEC/relawan/issues/91
> [Added]Laravolt foreign key pada tabel content_geometry_coordinates

- app/Services/PlaceService.php
> Memperbaiki isu halaman error ketika belum ada data posko

- app/Exceptions/Handler.php
- composer.json
- composer.lock
> integrate to smart notify

- app/Repositories/PlaceRepository.php
- resources/views/posko.blade.php
- Menambahkan conditions di posko blade, jika tidak ada data dan jika empty
- Menambahkan `return` di PlaceRepository
Perbaikan Issue #96
> Perbaikan untuk Issue #96

- package.json
Berdasarkan 
- https://github.com/NgeSEC/relawan/network/alert/package.json/axios/open
- https://nvd.nist.gov/vuln/detail/CVE-2019-10742
dan pembahasan di grup, 
axios tidak di gunakan, maka dependency axios di hapus, matur nuwun
> Menghapus axios
